require('luacfg.config')
require('luacfg.filetypes')
require('luacfg.neovide')
require('luacfg.remap')

require('luacfg.plugins.blink')
require('luacfg.plugins.comment')
require('luacfg.plugins.easymotion')
require('luacfg.plugins.gruvbox')
require('luacfg.plugins.harpoon')
require('luacfg.plugins.lsp')
require('luacfg.plugins.lualine')
require('luacfg.plugins.oil')
require('luacfg.plugins.telescope')
require('luacfg.plugins.vimwiki')
