{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit
    (lib)
    getExe
    ;

  backupPath = "/tmp/postgresql-dump.sql.zst";
in {
  chonkos.services.postgresql = {
    enable = true;
    version = 17;
  };

  services.restic.backups.computer = {
    paths = [backupPath];
  };

  chonkos.services.restic.backups.computer = {
    backupPrepareCommand =
      /*
      sh
      */
      ''
        ${config.services.postgresql.package}/bin/pg_dumpall --clean \
        | ${getExe pkgs.zstd} --rsyncable \
        > ${backupPath}
      '';

    backupCleanupCommand =
      /*
      sh
      */
      ''
        rm ${backupPath}
      '';
  };

  # Generated by https://pgconfigurator.cybertec.at/
  services.postgresql.settings = {
    # Connectivity
    max_connections = 100;
    superuser_reserved_connections = 3;

    # Memory Settings
    shared_buffers = "4096 MB";
    work_mem = "32 MB";
    maintenance_work_mem = "420 MB";
    huge_pages = "off";
    effective_cache_size = "11 GB";
    # concurrent IO "on"ly really activated if OS supports posix_fadvise function
    effective_io_concurrency = 100;
    # speed of random disk access relative to sequential access (1.0)
    random_page_cost = 1.25;

    # Monitoring
    # per statement resource usage stats
    shared_preload_libraries = "pg_stat_statements";
    # measure exact block IO times
    track_io_timing = "on";
    # track execution times of pl-language procedures if any
    track_functions = "pl";

    # Replication
    # consider using at least 'replica'
    wal_level = "replica";
    max_wal_senders = 0;
    synchronous_commit = "on";

    # Checkpointing:
    checkpoint_timeout = "15 min";
    checkpoint_completion_target = 0.9;
    max_wal_size = "1024 MB";
    min_wal_size = "512 MB";

    # WAL writing
    wal_compression = "on";
    # auto-tuned by Postgres till maximum of segment size (16MB by default)
    wal_buffers = -1;
    wal_writer_delay = "200ms";
    wal_writer_flush_after = "1MB";

    # Background writer
    bgwriter_delay = "200ms";
    bgwriter_lru_maxpages = 100;
    bgwriter_lru_multiplier = 2.0;
    bgwriter_flush_after = 0;

    # Parallel queries:
    max_worker_processes = 8;
    max_parallel_workers_per_gather = 4;
    max_parallel_maintenance_workers = 4;
    max_parallel_workers = 8;
    parallel_leader_participation = "on";

    # Advanced features
    enable_partitionwise_join = "on";
    enable_partitionwise_aggregate = "on";
    jit = "on";
    max_slot_wal_keep_size = "1000 MB";
    track_wal_io_timing = "on";
    maintenance_io_concurrency = 100;
    wal_recycle = "on";
  };
}
